import Link from "next/link";

export default function HelpPage() {
  return (
    <div className="mx-auto max-w-3xl p-8">
      <div className="flex items-center gap-3">
        <img src="/assets/SWeblogo1.jpg" alt="SIS" className="h-9 w-9 rounded-lg object-contain ring-1 ring-black/5" />
        <div>
          <h1 className="text-2xl font-semibold">SIS Console Help</h1>
          <p className="text-sm text-slate-500">PDF exports, scheduled crawls & branding</p>
        </div>
      </div>

      <div className="mt-8 space-y-6">
        <section className="rounded-xl border border-slate-200 bg-white p-6">
          <h2 className="text-sm font-semibold text-[#0B1D3A]">📄 Branded PDF Export</h2>
          <p className="mt-2 text-sm text-slate-600">Every audit can be exported as a white-label PDF using your org branding from <Link href="/settings" className="text-[#0B1D3A] underline">Settings</Link> (name, logoUrl, primaryColor).</p>
          <div className="mt-3 rounded-lg bg-slate-50 p-4 font-mono text-xs">
            <div>GET /api/projects/[id]/audit?format=pdf</div>
            <div className="mt-2 text-slate-500"># toggle branding</div>
            <div>?branded=1|0 & headerLogo=1|0 & footer=1|0 & colorize=1|0 & print=1</div>
          </div>
          <ul className="mt-3 list-disc pl-5 text-xs text-slate-600">
            <li><code>branded=0</code> → clean unbranded (neutral slate, no SIS header)</li>
            <li><code>headerLogo=0</code> → hide logo but keep colors</li>
            <li><code>footer=0</code> → hide “Generated by SIS Console” footer</li>
            <li><code>colorize=0</code> → force slate instead of primaryColor</li>
            <li><code>print=1</code> → auto-open print dialog</li>
          </ul>
          <p className="mt-2 text-xs text-slate-500">Use the toggle on <Link href="/reports" className="underline">Reports</Link> or <code>/projects/[id]/audit</code> — it builds the URL for you.</p>
        </section>

        <section className="rounded-xl border border-slate-200 bg-white p-6">
          <h2 className="text-sm font-semibold text-[#0B1D3A]">⏰ Scheduled Crawls (Cron)</h2>
          <p className="mt-2 text-sm text-slate-600">Set frequency per project on <code>New Project</code> or in the <code>Crawl Schedule</code> box on the project page. Options: <code>manual</code> / <code>daily</code> / <code>weekly</code> / <code>monthly</code>.</p>
          <div className="mt-3 rounded-lg bg-slate-50 p-4 font-mono text-xs">
            <div>GET /api/cron/crawl?secret=CRON_SECRET</div>
            <div className="mt-2 text-slate-500"># or header</div>
            <div>Authorization: Bearer CRON_SECRET</div>
            <div>x-cron-secret: CRON_SECRET</div>
          </div>
          <ul className="mt-3 list-disc pl-5 text-xs text-slate-600">
            <li>Finds projects where <code>nextCrawlAt ≤ now()</code> and <code>crawlFrequency</code> is daily/weekly/monthly</li>
            <li>Skips if a crawl is already queued/running</li>
            <li>Creates a queued crawl and bumps <code>nextCrawlAt</code> (+1d / +7d / +30d)</li>
            <li>If <code>CRON_SECRET</code> not set, endpoint is open (dev mode) — set it in <code>.env</code> for prod</li>
          </ul>
          <div className="mt-3 rounded-lg border border-amber-200 bg-amber-50 p-3 text-xs">
            <p className="font-semibold text-amber-800">Setup</p>
            <p className="mt-1 text-amber-700">Vercel Cron: add <code>GET /api/cron/crawl</code> daily. Or GitHub Actions / <code>curl</code> from any cron:</p>
            <code className="mt-1 block bg-white p-2 rounded">curl -H &quot;x-cron-secret: $CRON_SECRET&quot; https://your-domain/api/cron/crawl</code>
          </div>
        </section>

        <section className="rounded-xl border border-slate-200 bg-white p-6">
          <h2 className="text-sm font-semibold">Env</h2>
          <div className="mt-2 rounded-lg bg-slate-50 p-4 font-mono text-xs">
            <div>DATABASE_URL=&quot;file:./dev.db&quot;</div>
            <div>JWT_SECRET=&quot;...&quot;</div>
            <div>CRON_SECRET=&quot;pick-a-long-random-string&quot; # optional but recommended</div>
          </div>
          <p className="mt-2 text-xs text-slate-500">See <code>.env.example</code> and copy to <code>.env</code>.</p>
        </section>
      </div>

      <div className="mt-8 flex gap-3 text-sm">
        <Link href="/reports" className="rounded-lg bg-[#0B1D3A] px-4 py-2 text-white">Go to Reports</Link>
        <Link href="/settings" className="rounded-lg border border-slate-300 px-4 py-2 text-slate-700">Edit Branding</Link>
      </div>
    </div>
  );
}
